org.gradle.jvmargs=-Xmx1280m -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -XX:CICompilerCount=1 -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8 -Dhttp.keepAlive=false -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
